package BananaFructa.TTIEMultiblocks.PowerRework;

import mctmods.immersivetechnology.common.blocks.metal.tileentities.TileEntityAlternatorMaster;
import mctmods.immersivetechnology.common.blocks.metal.tileentities.TileEntityAlternatorSlave;
import net.minecraft.tileentity.TileEntity;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.gameevent.TickEvent;

import java.util.IdentityHashMap;
import java.util.Map;

/**
 * To get an actual reading on the produced power just getting the possible energy output flow is not enough. If more energy is produced that consumed the internal
 * buffers of the systems will fill and then the energy produced will appear as the maximum transferable energy. Since the modpack only uses few energy sources this handles
 * getting the actual true amount of energy generated by producers.
 */
@Mod.EventBusSubscriber
public class ActualPowerReader {

    private static Map<TileEntity,Integer> avalabileEnergy = new IdentityHashMap<>();

    public static int getActualPower(TileEntity tile, int maxReceive, boolean simulate) {
        return -1;
        /*if (avalabileEnergy.containsKey(tile)) {
            return getEnergy(tile,maxReceive,simulate);
        } else {
            if (tile instanceof TileEntityAlternatorSlave) {
                TileEntityAlternatorMaster te = ((TileEntityAlternatorSlave) tile).master();
                if (te !=   null) {
                    avalabileEnergy.put(tile, te.energyGenerated());
                    return getEnergy(tile,maxReceive,simulate);
                } else return -1;
            } else {
                return -1;
            }
        }*/
    }

    private static int getEnergy(TileEntity tile, int maxReceive, boolean simulate) {
        int avalabile = avalabileEnergy.get(tile);
        if (avalabile >= maxReceive) {
            if (!simulate) avalabileEnergy.put(tile,avalabile-maxReceive);
            return maxReceive;
        } else {
            if (!simulate) avalabileEnergy.put(tile,0);
            return avalabile;
        }
    }

    public static void substractAvalabiltiy(TileEntity te, int amount) {
        avalabileEnergy.put(te,avalabileEnergy.get(te)-amount);
    }

    @SubscribeEvent
    public static void onTick(TickEvent.ServerTickEvent event) {
        avalabileEnergy.clear();
    }

}
