package BananaFructa.TTIEMultiblocks.TileEntities;

import BananaFructa.TTIEMultiblocks.TTIEContent;
import BananaFructa.TTIEMultiblocks.Utils.PortType;
import BananaFructa.TTIEMultiblocks.Utils.SimplifiedMultiblockRecipe;
import BananaFructa.TTIEMultiblocks.Utils.SimplifiedTileEntityMultiblockMetal;
import BananaFructa.TiagThings.Utils;
import net.minecraft.item.ItemStack;
import net.minecraft.util.EnumFacing;
import net.minecraftforge.fluids.FluidStack;

import java.util.ArrayList;
import java.util.List;

public class TileEntityElectricFoodOven extends SimplifiedTileEntityMultiblockMetal<TileEntityElectricFoodOven, SimplifiedMultiblockRecipe> {

    static private final int time = 30 * 20;
    static private final int energy = 150;
    static private String[] items = new String[]{
            "<tfcflorae:food/rowan_berry>",
            "<tfcflorae:food/dried/rowan_berry>",
            "<tfcflorae:food/pink_ivory_drupe>",
            "<tfcflorae:food/dried/pink_ivory_drupe>",
            "<tfcflorae:food/osage_orange>",
            "<tfcflorae:food/dried/osage_orange>",
            "<tfcflorae:food/green_grape>",
            "<tfcflorae:food/dried/green_grape>",
            "<tfcflorae:food/purple_grape>",
            "<tfcflorae:food/dried/purple_grape>",
            "<tfcflorae:food/yew_berry>",
            "<tfcflorae:food/dried/yew_berry>",
            "<tfcflorae:food/riberry>",
            "<tfcflorae:food/dried/riberry>",
            "<tfcflorae:food/hawthorn>",
            "<tfcflorae:food/dried/hawthorn>",
            "<tfcflorae:food/barrel_cactus_fruit>",
            "<tfcflorae:food/dried/barrel_cactus_fruit>",
            "<tfcflorae:food/baobab_fruit>",
            "<tfcflorae:food/dried/baobab_fruit>",
            "<tfcflorae:crop/product/sunflower_head>",
            "<tfcflorae:crop/product/dried/sunflower_head>",
            "<tfcflorae:crop/product/labrador_tea_head>",
            "<tfcflorae:crop/product/dried/labrador_tea_head>",
            "<tfcflorae:crop/product/dandelion_head>",
            "<tfcflorae:crop/product/dried/dandelion_head>",
            "<tfcflorae:crop/product/chamomile_head>",
            "<tfcflorae:crop/product/dried/chamomile_head>",
            "<tfcflorae:food/coffea_cherries>",
            "<tfcflorae:food/dried/coffea_cherries>",
            "<tfcflorae:food/tobacco_leaf>",
            "<tfcflorae:food/dried/tobacco_leaf>",
            "<tfcflorae:food/peyote>",
            "<tfcflorae:food/dried/peyote>",
            "<tfcflorae:food/opium_poppy_bulb>",
            "<tfcflorae:food/dried/opium_poppy_bulb>",
            "<tfcflorae:food/coca_leaf>",
            "<tfcflorae:food/dried/coca_leaf>",
            "<tfcflorae:food/cannabis_leaf>",
            "<tfcflorae:food/dried/cannabis_leaf>",
            "<tfcflorae:food/cannabis_bud>",
            "<tfcflorae:food/dried/cannabis_bud>",
            "<tfcflorae:food/white_tea>",
            "<tfcflorae:food/dried/white_tea>",
            "<tfcflorae:food/green_tea>",
            "<tfcflorae:food/dried/green_tea>",
            "<tfcflorae:food/black_tea>",
            "<tfcflorae:food/dried/black_tea>",
            "<tfcflorae:cellulose_fibers>",
            "<minecraft:paper>",
            "<firmalife:pineapple>",
            "<firmalife:dried_pineapple>",
            "<firmalife:cocoa_beans>",
            "<firmalife:dried_cocoa_beans>",
            "<firmalife:cinnamon_bark>",
            "<firmalife:cinnamon>",
            "<tfc:food/wintergreen_berry>",
            "<firmalife:dried_wintergreen_berry>",
            "<firmalife:rye_flatbread_dough>",
            "<firmalife:rye_flatbread>",
            "<tfc:food/strawberry>",
            "<firmalife:dried_strawberry>",
            "<tfc:food/snow_berry>",
            "<firmalife:dried_snow_berry>",
            "<tfc:food/red_apple>",
            "<firmalife:dried_red_apple>",
            "<tfc:food/raspberry>",
            "<firmalife:dried_raspberry>",
            "<tfc:food/plum>",
            "<firmalife:dried_plum>",
            "<tfc:food/peach>",
            "<firmalife:dried_peach>",
            "<tfc:food/orange>",
            "<firmalife:dried_orange>",
            "<tfc:food/olive>",
            "<firmalife:dried_olive>",
            "<tfcflorae:food/quinoa_flatbread_dough>",
            "<tfcflorae:food/quinoa_flatbread>",
            "<tfc:food/lemon>",
            "<firmalife:dried_lemon>",
            "<tfc:food/green_apple>",
            "<firmalife:dried_green_apple>",
            "<tfc:food/gooseberry>",
            "<firmalife:dried_gooseberry>",
            "<tfc:food/elderberry>",
            "<firmalife:dried_elderberry>",
            "<tfc:food/cranberry>",
            "<firmalife:dried_cranberry>",
            "<tfc:food/cloud_berry>",
            "<firmalife:dried_cloud_berry>",
            "<tfc:food/cherry>",
            "<firmalife:dried_cherry>",
            "<tfc:food/bunch_berry>",
            "<firmalife:dried_bunch_berry>",
            "<tfc:food/blueberry>",
            "<firmalife:dried_blueberry>",
            "<firmalife:rice_flatbread_dough>",
            "<firmalife:rice_flatbread>",
            "<tfc:food/blackberry>",
            "<firmalife:dried_blackberry>",
            "<tfc:food/banana>",
            "<firmalife:dried_banana>",
            "<firmalife:pizza_dough>",
            "<firmalife:cooked_pizza>",
            "<tfcflorae:food/amaranth_dough>",
            "<tfcflorae:food/amaranth_bread>",
            "<tfcflorae:food/buckwheat_dough>",
            "<tfcflorae:food/buckwheat_bread>",
            "<tfcflorae:food/fonio_dough>",
            "<tfcflorae:food/fonio_bread>",
            "<tfcflorae:food/millet_dough>",
            "<tfcflorae:food/millet_bread>",
            "<tfcflorae:food/quinoa_dough>",
            "<tfcflorae:food/quinoa_bread>",
            "<tfcflorae:food/spelt_dough>",
            "<tfcflorae:food/spelt_bread>",
            "<tfcflorae:food/hash_muffin_dough>",
            "<tfcflorae:food/hash_muffin>",
            "<tfc:food/barley_dough>",
            "<tfc:food/barley_bread>",
            "<tfc:food/cornmeal_dough>",
            "<tfc:food/cornbread>",
            "<tfc:food/oat_dough>",
            "<tfc:food/oat_bread>",
            "<tfc:food/rice_dough>",
            "<tfc:food/rice_bread>",
            "<tfc:food/rye_dough>",
            "<tfc:food/rye_bread>",
            "<tfc:food/wheat_dough>",
            "<tfc:food/wheat_bread>",
            "<firmalife:chestnut_dough>",
            "<firmalife:chestnut_bread>",
            "<firmalife:chestnuts>",
            "<firmalife:roasted_chestnuts>",
            "<firmalife:dried_cocoa_beans>",
            "<firmalife:roasted_cocoa_beans>",
            "<tfcflorae:food/dried/yew_berry>",
            "<tfcflorae:food/roasted/yew_berry>",
            "<tfcflorae:food/beechnut_nut>",
            "<tfcflorae:food/roasted/beechnut_nut>",
            "<tfcflorae:food/black_walnut_nut>",
            "<tfcflorae:food/roasted/black_walnut_nut>",
            "<tfcflorae:food/butternut_nut>",
            "<tfcflorae:food/roasted/butternut_nut>",
            "<tfcflorae:food/ginkgo_nut_nut>",
            "<tfcflorae:food/roasted/ginkgo_nut_nut>",
            "<tfcflorae:food/hazelnut_nut>",
            "<tfcflorae:food/roasted/hazelnut_nut>",
            "<tfcflorae:food/walnut_nut>",
            "<tfcflorae:food/roasted/walnut_nut>",
            "<tfc:plants/artists_conk>",
            "<tfcflorae:food/roasted/artists_conk>",
            "<tfc:plants/sulphur_shelf>",
            "<tfcflorae:food/roasted/sulphur_shelf>",
            "<tfc:plants/turkey_tail>",
            "<tfcflorae:food/roasted/turkey_tail>",
            "<tfc:plants/porcini>",
            "<tfcflorae:food/roasted/porcini>",
            "<tfc:plants/amanita>",
            "<tfcflorae:food/roasted/amanita>",
            "<tfc:plants/black_powderpuff>",
            "<tfcflorae:food/roasted/black_powderpuff>",
            "<tfc:plants/chanterelle>",
            "<tfcflorae:food/roasted/chanterelle>",
            "<tfc:plants/death_cap>",
            "<tfcflorae:food/roasted/death_cap>",
            "<tfc:plants/giant_club>",
            "<tfcflorae:food/roasted/giant_club>",
            "<tfc:plants/parasol_mushroom>",
            "<tfcflorae:food/roasted/parasol_mushroom>",
            "<tfc:plants/stinkhorn>",
            "<tfcflorae:food/roasted/stinkhorn>",
            "<tfc:plants/weeping_milk_cap>",
            "<tfcflorae:food/roasted/weeping_milk_cap>",
            "<tfc:plants/wood_blewit>",
            "<tfcflorae:food/roasted/wood_blewit>",
            "<tfc:plants/woolly_gomphus>",
            "<tfcflorae:food/roasted/woolly_gomphus>",
            "<tfcflorae:food/dried/coffea_cherries>",
            "<tfcflorae:food/roasted/coffee_beans>",
            "<minecraft:bone>",
            "<tfcflorae:charred_bones>",
            "<tfcflorae:ceramics/kaolinite/kaolinite_clay>",
            "<tfc:powder/kaolinite>",
            "<tfcflorae:food/fonio_flatbread_dough>",
            "<tfcflorae:food/fonio_flatbread>",
            "<tfcflorae:food/raw_worm>",
            "<tfcflorae:food/cooked_worm>",
            "<tfcflorae:food/raw_snail>",
            "<tfcflorae:food/cooked_snail>",
            "<tfcflorae:food/raw_starfish>",
            "<tfcflorae:food/cooked_starfish>",
            "<tfcflorae:food/raw_scallop>",
            "<tfcflorae:food/cooked_scallop>",
            "<tfcflorae:food/raw_clam>",
            "<tfcflorae:food/cooked_clam>",
            "<tfcflorae:food/raw_crab>",
            "<tfcflorae:food/cooked_crab>",
            "<tfcflorae:food/raw_eel>",
            "<tfcflorae:food/cooked_eel>",
            "<firmalife:milk_chocolate_blend>",
            "<firmalife:milk_chocolate>",
            "<firmalife:dark_chocolate_blend>",
            "<firmalife:dark_chocolate>",
            "<firmalife:barley_flatbread_dough>",
            "<firmalife:barley_flatbread>",
            "<tfcflorae:food/buckwheat_flatbread_dough>",
            "<tfcflorae:food/buckwheat_flatbread>",
            "<tfcflorae:food/spelt_flatbread_dough>",
            "<tfcflorae:food/spelt_flatbread>",
            "<firmalife:corn_flatbread_dough>",
            "<firmalife:corn_flatbread>",
            "<firmalife:oat_flatbread_dough>",
            "<firmalife:oat_flatbread>",
            "<tfcflorae:food/amaranth_flatbread_dough>",
            "<tfcflorae:food/amaranth_flatbread>",
            "<tfcflorae:food/millet_flatbread_dough>",
            "<tfcflorae:food/millet_flatbread>",
            "<firmalife:wheat_flatbread_dough>",
            "<firmalife:wheat_flatbread>"
    };

    public static List<SimplifiedMultiblockRecipe> recipes = new ArrayList<SimplifiedMultiblockRecipe>() {{
        for (int i = 0;i < items.length;i+=2) {
            add(new SimplifiedMultiblockRecipe(new ItemStack[]{Utils.itemStackFromCTId(items[i])},new FluidStack[0], new ItemStack[]{Utils.itemStackFromCTId(items[i+1])},new FluidStack[0],energy,time,true));
        }
    }};
    public TileEntityElectricFoodOven() {
        super(TTIEContent.electricFoodOven, 16000, false,recipes);
    }

    @Override
    public void initPorts() {
        addEnergyPort(71);
        int itemIn = registerItemHandler(1,new boolean[]{true},new boolean[]{true});
        registerItemPort(64,itemIn, PortType.INPUT, EnumFacing.WEST);
        int itemOut = registerItemHandler(1,new boolean[]{true},new boolean[]{true});
        registerItemPort(53,itemOut,PortType.OUTPUT,EnumFacing.EAST);
    }
}
